version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: rbac sample app  Build and push Docker image
          command: |
            sudo docker build -t cloudplexng/k8s-rbac:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push cloudplexng/k8s-rbac:${CIRCLE_BUILD_NUM}