version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: rbac fet information Build and push Docker image
          command: |
            sudo docker build -t cloudplexng/dockerfet:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push cloudplexng/dockerfet:${CIRCLE_BUILD_NUM}